alias: peer_24
mnemonic: pistol kiwi shrug future ozone ostrich match remove crucial oblige cream
  critic
accountIndex: 24
channel:
  timeout: 30s
  fundtimeout: 30s
  settleTimeout: 30s
  challengeDurationSec: 60
node:
  ip: 0.0.0.0
  port: 5774
  dialTimeout: 30s
  handleTimeout: 30s
  reconnectTimeout: 20s
  persistencePath: /tmp/peer_24
  apiPort: 8105
chain:
  url: ws://127.0.0.1:8545
  contractsetup: validate
  adjudicator: 0x079557d7549d7D44F4b00b51d2C532674129ed51
  assetholder: 0x923439be515b6a928cb9650d70000a9044e49e85
  app: 0xe72d67D4d7CB437D086445Be955385dD520Bfe11
  txTimeout: 30s
  txFinalityDepth: 3
  ID: 1337
log:
  level: warn
  file: logs/peer_24.log
walletPath: /tmp/peer_24_wallet
secretKey: 0x9e86c6461dd3cc4fc67ff1d38806795553cb7bf0c9a8ff18fb92e6ca210f48a9
